version: "3.9"

networks:
  server-network:
    driver: bridge

services:
  main:
    build :  
      context: .
      dockerfile:  ./apps/main/Dockerfile
    restart: always
    hostname: localhost
    env_file :
      - .env
    ports:
      - 3000:3000
    networks:
      - server-network

  auth:
    build :  
      context: .
      dockerfile:  ./apps/auth/Dockerfile
    restart: always
    hostname: localhost
    env_file :
      - .env

    ports:
      - 3001:3001
    networks:
      - server-network
  
